### ISSUE TITLE
无法续期，报错Renew Error!

### ISSUE THREAD

**Issue by karma-sun** [zing555/EUserv_extend#1]
无法续期，报错Renew Error!

**Comment by lony2003** [comment]
这个仓库里的代码已经不适用于新版的面板了，新版面板添加了机器人验证和续费时的邮箱验证，这个代码已经不能支持这两个东西了（说实话想支持也是很困难了），如果你感兴趣的话可以参考一下其他人的代码然后对这个做一些修改再用，当然，如果你是用国内的邮箱注册的euserv的话就别费那个劲了，还是等它给你微信发错误的时候自己续费一下好了（还有，最近server酱的api更新了，好像这个版本的server酱也用不了。。。。。。。）
